let me=null, selectedImport=null, pendingImport=null, chatConfig={}, mapLoaded=false, conversation=[], chatEpoch=0;
const adminLoginNote=el('p','Admin users sign in here too. The Coordination dashboard appears after local administrator access is enabled.','small');$('login-form')?.prepend(adminLoginNote);
function coordinationView(){if($('coordination'))return;const link=el('a','Coordination dashboard');link.href='#coordination';link.className='admin-only';link.hidden=true;document.querySelector('nav').append(link);const section=el('section');section.id='coordination';section.className='view';section.hidden=true;section.innerHTML='<p class="eyebrow">CLINICAL AND PARTNER WORK QUEUE</p><h1 class="page-title">Coordination dashboard</h1><p class="intro">Review appointment requests and follow-up tasks. This local dashboard does not send notifications or contact a facility.</p><div class="metric-grid" id="coordination-metrics"></div><div class="panel"><h2>Appointments</h2><div class="table-scroll"><table><thead><tr><th>Facility</th><th>Requested for</th><th>Reason</th><th>Status</th><th>Acknowledged</th><th>Action</th></tr></thead><tbody id="appointment-rows"></tbody></table></div></div><div class="panel"><h2>Follow-up tasks</h2><div class="table-scroll"><table><thead><tr><th>Task</th><th>Due</th><th>Status</th><th>Acknowledged</th><th>Action</th></tr></thead><tbody id="followup-rows"></tbody></table></div></div>';$('home').parentElement.insertBefore(section,$('home'))}
async function loadCoordination(){coordinationView();const dashboard=await api('dashboard/coordination');const appointments=dashboard.appointments,followups=dashboard.follow_ups;$('coordination-metrics').replaceChildren(...[[appointments.filter(x=>x.status==='requested').length,'Requested appointments'],[appointments.filter(x=>x.status==='confirmed').length,'Confirmed appointments'],[followups.filter(x=>x.status==='open').length,'Open follow-ups']].map(([value,label])=>{const c=el('div',undefined,'metric');c.append(el('b',String(value)),el('span',label));return c}));const appointmentRows=$('appointment-rows');appointmentRows.replaceChildren();appointments.forEach(item=>{const row=el('tr');[item.facility_id,item.requested_for,item.reason,item.status,item.acknowledged?'Yes':'No'].forEach(value=>row.append(el('td',value)));const action=el('td');if(!item.acknowledged){const b=el('button','Acknowledge','button secondary');b.onclick=async()=>{await api(`appointments/${item.id}/acknowledge`,{method:'POST'});loadCoordination()};action.append(b)}else if(['requested','confirmed'].includes(item.status)){const b=el('button','Mark completed','button secondary');b.onclick=async()=>{await api(`appointments/${item.id}`,{method:'PATCH',body:JSON.stringify({status:'completed'})});loadCoordination()};action.append(b)}row.append(action);appointmentRows.append(row)});const followupRows=$('followup-rows');followupRows.replaceChildren();followups.forEach(item=>{const row=el('tr');[item.task,item.due_at,item.status,item.acknowledged?'Yes':'No'].forEach(value=>row.append(el('td',value)));const action=el('td');if(!item.acknowledged){const b=el('button','Acknowledge','button secondary');b.onclick=async()=>{await api(`follow-ups/${item.id}/acknowledge`,{method:'POST'});loadCoordination()};action.append(b)}if(item.status==='open'){const b=el('button','Complete','button secondary');b.onclick=async()=>{await api(`follow-ups/${item.id}`,{method:'PATCH',body:JSON.stringify({status:'completed'})});loadCoordination()};action.append(b)}row.append(action);followupRows.append(row)})}
const accountEvents='BroadcastChannel' in window?new BroadcastChannel('mama-link-account'):null;
if(accountEvents)accountEvents.onmessage=()=>{resetPrivateUI();location.reload()};
const baseApi=api;
api=async function(path,options={}){
 const identityIndependent=['me','login','register','logout','options','education'].includes(path);
 if(me&&!identityIndependent)options={...options,headers:{...options.headers,'X-Mama-Account':me.id}};
 try{const result=await baseApi(path,options);if(['login','register','logout'].includes(path))accountEvents?.postMessage('changed');return result}
 catch(error){if(error.message.includes('account changed')||error.message==='Please sign in first'){resetPrivateUI();me=null;location.reload()}throw error}
};
document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'){try{const state=await baseApi('me');if((state.user?.id||null)!==(me?.id||null)){resetPrivateUI();location.reload()}}catch{}}});
const nullable=id=>$(id).value===''?null:Number($(id).value);
function appointmentCard(record,candidates,registry=false){const appointment=el('div',undefined,'result-card');appointment.append(el('h2','Request an appointment'),el('p',registry?'No clinical referral match was available, but these status-qualified registry facilities match your location. Confirm services and availability before requesting a visit.':'Choose a matched facility and a preferred time. This creates a local request for the coordination dashboard; it does not contact the facility.'));if(!candidates.length){appointment.append(el('p','No facility record matches the location entered. Use Find care to review another state or LGA.','status-note'));return appointment}const facility=el('select');candidates.forEach(f=>{const option=el('option',`${f.name} · ${f.lga}`);option.value=f.facility_id;facility.append(option)});const when=el('input');when.type='datetime-local';when.required=true;const reason=el('input');reason.value='Follow-up review';reason.maxLength=300;reason.required=true;const submit=el('button','Request appointment','button primary');submit.type='button';submit.onclick=async()=>{if(!when.value||!reason.value.trim())return showError(new Error('Choose a date, time and reason first.'));submit.disabled=true;try{await api('appointments',{method:'POST',body:JSON.stringify({assessment_id:record.id,facility_id:facility.value,requested_for:new Date(when.value).toISOString(),reason:reason.value.trim()})});appointment.replaceChildren(el('h2','Appointment request submitted'),el('p','Your request is waiting for coordination review. No notification was sent.','status-note'))}catch(e){showError(e)}finally{submit.disabled=false}};appointment.append(el('label','Facility'),facility,el('label','Preferred date and time'),when,el('label','Reason'),reason,submit);return appointment}
const oldRender=renderAssessment;
renderAssessment=function(record){
 oldRender(record);const source=el('details',undefined,'result-card');source.append(el('summary','Where this check-in’s data came from'));
 const rows=Object.entries(record.case.provenance||{}).map(([k,v])=>`${pretty(k)}: ${record.case.readings[k]?.value} ${v.unit||''} · ${pretty(v.source)}${v.device?' · '+v.device:''}${v.measured_at?' · '+new Date(v.measured_at).toLocaleString():''}`);
 source.append(list(rows.length?rows:['No measurements supplied. Missing readings were not filled with normal values.']),el('p','Your answers → validated check-in → screening and previous-check-in comparison → care and resource matching → your private log. Chat receives a limited summary only with consent.'));$('assessment-output').append(source);
 const support=el('div',undefined,'result-card');support.append(el('h2','Practical support'));if(record.result.support.length)record.result.support.forEach(s=>support.append(el('p',`${s.name||s.organization||s.resource_id||'Support resource'} · ${pretty(s.service_type||s.service||s.services?.join(', ')||'Referral support')}`)));else support.append(el('p','No matching support resource is listed. Ask a local health worker about available services.'));support.append(el('p','Demonstration resources; live availability has not been confirmed.','small'));$('assessment-output').append(support);
 let appointment=appointmentCard(record,record.result.facilities);$('assessment-output').append(appointment);if(!record.result.facilities.length&&record.case.location?.state){const query=new URLSearchParams({state:record.case.location.state,lga:record.case.location.lga||'',limit:'50',verified_only:'true'});api(`facilities?${query}`).then(data=>{if(data.facilities.length){appointment=appointmentCard(record,data.facilities,true);const current=[...$('assessment-output').children].find(node=>node.querySelector?.('h2')?.textContent==='Request an appointment');if(current)current.replaceWith(appointment)}}).catch(()=>{});}
};
function resetPrivateUI(){
 chatEpoch++;conversation=[];current=null;selectedImport=null;pendingImport=null;cases=[];$('assessment-form').reset();$('fixture-summary').replaceChildren();$('fixture-controls').hidden=true;$('case-select').replaceChildren(el('option','My own check-in'));$('case-select').firstChild.value='';$('assessment-output').replaceChildren(el('p','Your next check-in will appear here.','panel'));$('history-list').replaceChildren();$('device-imports').replaceChildren();$('device-preview').textContent='';$('device-preview').hidden=true;$('device-file').value='';$('device-reviewed').checked=false;$('device-import').disabled=true;$('chat-messages').replaceChildren(el('p','Hello. What’s on your mind today?','chat-bubble bot'));$('chat-form').reset();$('profile-form').reset();$('login-form').reset();$('register-form').reset();$('import-selection').textContent='No health-app readings selected. Manual entry is always available.';
}
function applyProfile(){
 if(!me)return;const p=me.profile;for(const [id,key] of Object.entries({'profile-name':'name','profile-age':'age','profile-stage':'pregnancy_stage','profile-weeks':'gestational_age','profile-days':'postpartum_day','profile-state':'state','profile-place':'place','profile-language':'language','profile-medications':'medications','profile-allergies':'allergies'}))$(id).value=p[key]??'';
 $('age').value=p.age??'';$('stage').value=p.pregnancy_stage;$('gestation').value=p.gestational_age??'';$('postpartum').value=p.postpartum_day??'';$('state').value=p.state||'';fillPlaces('state','lga');if(p.place)$('lga').value=p.place;$('language').value=p.language;applyLanguage();$('assessment-person').textContent=`Checking in as ${p.name}. You can update the details below.`;$('welcome').textContent=`Hello, ${p.name}. How are you feeling today?`;$('journey-stage').textContent=p.pregnancy_stage==='unknown'?'Your journey, at your pace':pretty(p.pregnancy_stage)+(p.gestational_age?` · ${p.gestational_age} weeks`:'');$('chat-context').textContent=`Your profile: ${pretty(p.pregnancy_stage)}${p.gestational_age?`, ${p.gestational_age} weeks`:''}. Your name is used on screen, not sent to the AI.`;
}
async function refreshIdentity(){
 coordinationView();
 const state=await api('me');me=state.user;chatConfig=state.chat;document.querySelectorAll('.admin-only').forEach(n=>n.hidden=me?.role!=='admin');$('logout').hidden=!me;$('account-link').hidden=!!me;$('account-label').textContent=me?`${me.profile.name} · ${me.role==='admin'?'Administrator':'My personal space'}`:'Your pregnancy. Your space.';
 $('chat-model').textContent=chatConfig.specialist_configured?`Configured health-model deployment: ${chatConfig.model}. Responses still need clinical review.`:chatConfig.configured?`Foundry education assistant · ${chatConfig.model}. A medically trained specialist model is not deployed.`:'Online assistant unavailable. Learning cards remain available.';
 if(me){applyProfile();if(me.role==='admin'){cases=await api('cases');cases.forEach(c=>{const o=el('option',`${c.case_id} · ${c.location.state}`);o.value=c.case_id;$('case-select').append(o)})}}else{$('welcome').textContent='A little support. Every step of the way.';$('journey-stage').textContent='Create your personal pregnancy profile'}$('case-select').value='';displayFixture();
}
const originalRoute=route;window.removeEventListener('hashchange',originalRoute);
route=async function(){let id=location.hash.slice(1)||'home';if(!['home','assess','care','hotspots','history','evaluate','account','profile','devices','chat','learn'].includes(id))id='home';if(['assess','history','profile','devices','chat','hotspots','evaluate'].includes(id)&&!me)id='account';if(['hotspots','evaluate'].includes(id)&&me?.role!=='admin')id='home';if(!$('chat').hidden&&id!=='chat'){chatEpoch++;conversation=[];$('chat-messages').replaceChildren(el('p','Hello. What’s on your mind today?','chat-bubble bot'));$('chat-form').reset()}document.querySelectorAll('.view').forEach(s=>s.hidden=s.id!==id);document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+id));$('notice').hidden=true;try{if(id==='history')await loadHistory();if(id==='evaluate')await loadEvaluation();if(id==='devices')await loadDevices();if(id==='hotspots'&&!mapLoaded){hotspotData=await api('hotspots');await renderMap();mapLoaded=true}}catch(e){showError(e)}};
window.addEventListener('hashchange',()=>route());
const personalRoute=route;
route=async function(){const id=location.hash.slice(1);if(id==='coordination'){if(!me||me.role!=='admin'){location.hash='home';return}document.querySelectorAll('.view').forEach(s=>s.hidden=s.id!==id);document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+id));$('notice').hidden=true;try{await loadCoordination()}catch(e){showError(e)}return}return personalRoute()};
async function authenticate(e,register){e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const prefix=register?'register':'login',body={username:$(prefix+'-user').value,password:$(prefix+'-password').value};if(register)body.profile={name:$('register-name').value,synthetic:$('register-synthetic').checked};await api(register?'register':'login',{method:'POST',body:JSON.stringify(body)});resetPrivateUI();await refreshIdentity();location.hash=register?'profile':'home';await route()}catch(x){showError(x)}finally{button.disabled=false}}
$('login-form').onsubmit=e=>authenticate(e,false);$('register-form').onsubmit=e=>authenticate(e,true);
$('logout').onclick=async()=>{try{await api('logout',{method:'POST'});resetPrivateUI();await refreshIdentity();location.hash='home';await route()}catch(e){showError(e)}};
$('profile-form').onsubmit=async e=>{e.preventDefault();const p={name:$('profile-name').value,age:nullable('profile-age'),pregnancy_stage:$('profile-stage').value,gestational_age:nullable('profile-weeks'),postpartum_day:nullable('profile-days'),state:$('profile-state').value,place:$('profile-place').value,language:$('profile-language').value,medications:$('profile-medications').value,allergies:$('profile-allergies').value,synthetic:true};try{await api('profile',{method:'PUT',body:JSON.stringify(p)});me.profile=p;applyProfile();$('profile-saved').textContent=' Saved.'}catch(x){showError(x)}};
$('assessment-form').onsubmit=async e=>{e.preventDefault();$('assess-submit').disabled=true;try{const body=$('case-select').value?{case_id:$('case-select').value}:{case:customInput(),import_id:selectedImport};renderAssessment(await api('assessments',{method:'POST',body:JSON.stringify(body)}))}catch(x){showError(x)}finally{$('assess-submit').disabled=false}};
function samplePayload(){return{source:'sample_device',provider:$('device-provider').value,device_name:'Fictional '+$('device-provider').selectedOptions[0].text+' sample',synthetic:true,reviewed:true,measurements:[{metric:'heart_rate',value:82,unit:'bpm',measured_at:new Date().toISOString()},{metric:'temperature',value:36.8,unit:'C',measured_at:new Date().toISOString()}]}}
function previewImport(p){pendingImport=p;$('device-preview').textContent=[p.device_name||'Health-app import', 'Source: '+pretty(p.provider||'other')+' · '+pretty(p.source||'unknown'), ...(p.measurements||[]).map(m=>pretty(m.metric)+': '+m.value+' '+m.unit+' · '+new Date(m.measured_at).toLocaleString())].join('\n');$('device-preview').hidden=false;$('device-reviewed').checked=false;$('device-import').disabled=false}
document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{$('device-provider').value=b.dataset.provider;$('device-provider').focus()});$('device-sample').onclick=()=>previewImport(samplePayload());
$('device-file').onchange=async()=>{try{const f=$('device-file').files[0];if(!f)return;if(f.size>32768)throw Error('Choose a JSON file smaller than 32 KB.');previewImport(JSON.parse(await f.text()))}catch(e){pendingImport=null;$('device-import').disabled=true;showError(e)}};
$('connector-example').onclick=e=>{e.preventDefault();const blob=new Blob([JSON.stringify(samplePayload(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='mama-link-connector-example.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('device-enabled').onchange=async()=>{try{await api('device',{method:'PUT',body:JSON.stringify({enabled:$('device-enabled').checked})});if(!$('device-enabled').checked){selectedImport=null;pendingImport=null;$('device-import').disabled=true;$('device-preview').hidden=true;$('import-selection').textContent='Health-app imports turned off. You can enter readings yourself.'}await loadDevices()}catch(e){showError(e)}};
$('device-import').onclick=async()=>{if(!pendingImport||!$('device-reviewed').checked)return showError(Error('Review the readings and confirm first.'));try{await api('device/import',{method:'POST',body:JSON.stringify({...pendingImport,reviewed:true})});pendingImport=null;$('device-preview').hidden=true;$('device-import').disabled=true;await loadDevices()}catch(e){showError(e)}};
async function loadDevices(){const d=await api('device');$('device-enabled').checked=d.enabled;$('device-imports').replaceChildren();for(const r of d.imports){const card=el('div',undefined,'import-row');card.append(el('h3',r.device_name),el('p',`${pretty(r.source)} · ${pretty(r.provider||'other')} · ${r.measurements.map(m=>`${pretty(m.metric)} ${m.value} ${m.unit}`).join(' / ')}`));const b=el('button','Use in next check-in','button secondary');b.onclick=()=>{selectedImport=r.id;$('case-select').value='';displayFixture();['systolic','diastolic','temperature','heart-rate'].forEach(id=>$(id).value='');$('import-selection').textContent=`Selected: ${r.device_name}. Imported values are used where manual fields are blank; manual changes take priority.`;location.hash='assess'};card.append(b);$('device-imports').append(card)}}
$('chat-form').onsubmit=async e=>{e.preventDefault();const text=$('chat-question').value,epoch=chatEpoch;$('chat-send').disabled=true;$('chat-send').textContent='Thinking…';$('chat-messages').append(el('p',text,'chat-bubble woman'));try{const r=await api('chat',{method:'POST',body:JSON.stringify({message:text,share_context:$('chat-consent').checked,conversation:conversation.slice(-8)})});if(epoch!==chatEpoch)return;conversation.push({role:'user',content:text},{role:'assistant',content:r.answer});const bubble=el('div',undefined,'chat-bubble bot');bubble.append(el('p',r.answer),el('small',`${pretty(r.mode)}${r.model?' · '+r.model:''}${r.context_used.length?' · Context: '+r.context_used.join(', '):''}`));for(const url of r.sources){const a=el('a','Reference material ↗','source-link');a.href=url;a.target='_blank';a.rel='noopener noreferrer';bubble.append(a)}$('chat-messages').append(bubble);$('chat-question').value=''}catch(x){showError(x)}finally{$('chat-send').disabled=false;$('chat-send').textContent='Send question'}};
async function personalInit(){try{const options=await api('options');facilities=options.facilities;locations=options.locations;services=options.national_services;for(const id of ['state','care-state','profile-state']){$(id).replaceChildren();const empty=el('option','Choose a state (optional)');empty.value='';$(id).append(empty);locations.forEach(x=>{const o=el('option',x.name);o.value=x.name;$(id).append(o)})}fillPlaces('state','lga');fillPlaces('care-state','care-lga');const labels={pallor_reported:'Looking unusually pale',fetal_movement_present:'I can feel my baby moving',visual_disturbance:'Changes in my vision',breathlessness_at_rest:'Hard to breathe even while resting',reported_prolonged_or_obstructed_labour:'Labour is taking very long or feels blocked',swelling_hands_face:'Swollen hands or face',foul_smelling_discharge:'Discharge with an unpleasant smell',unable_to_keep_fluids:'I cannot keep drinks down',social_isolation_concern:'I feel alone or without support',heavy_bleeding:'Heavy bleeding',severe_headache:'A very bad headache',blurred_vision:'Blurred vision',seizure:'A seizure or convulsion',shortness_of_breath:'Finding it hard to breathe',reduced_fetal_movement:'Baby moving less than usual'};options.symptoms.forEach(s=>{const l=el('label'),c=el('input');c.type='checkbox';c.value=s;l.append(c,document.createTextNode(labels[s]||pretty(s)));$('symptoms').append(l)});[...new Set(facilities.flatMap(f=>f.capabilities))].sort().forEach(x=>{const o=el('option',pretty(x));o.value=x;$('capability-filter').append(o)});groupSymptoms();registryCard();renderFacilities();$('emergency-source').href=services.emergency.source;setupVoice();const learning=await api('education');for(const a of learning.articles){const card=el('article',undefined,'panel');card.append(el('h2',a.title),el('p',a.text));const link=el('a','Read source ↗','source-link');link.href=a.source;link.target='_blank';link.rel='noopener noreferrer';card.append(link);const b=el('button','Listen','button secondary');b.disabled=!('speechSynthesis'in window);b.onclick=()=>{speechSynthesis.cancel();const s=new SpeechSynthesisUtterance(a.title+'. '+a.text);s.lang='en-NG';speechSynthesis.speak(s)};card.append(b);$('learning-cards').append(card)}await refreshIdentity();await route()}catch(e){showError(e)}}
window.addEventListener('offline',()=>{$('connection-label').textContent='Offline · open your downloaded learning guide. Check-ins and chat need a connection.'});window.addEventListener('online',()=>{$('connection-label').textContent='Low-data mode · maps load only on request'});function groupSymptoms(){const urgent=new Set(['heavy_bleeding','seizure','chest_pain','severe_breathlessness','loss_of_consciousness','severe_headache','visual_disturbance','reduced_fetal_movement','severe_abdominal_pain']);const common=new Set(['mild_nausea','fatigue','fever','dizziness','swelling_hands_face','social_isolation_concern']);const extra=el('details');extra.append(el('summary','More symptoms and changes'));const other=el('div',undefined,'symptom-list');for(const label of [...$('symptoms').children]){const key=label.querySelector('input').value;if(!urgent.has(key)&&!common.has(key))other.append(label)}extra.append(other);$('symptoms').append(extra)}personalInit().then(()=>{$('care-state').value='Lagos';fillPlaces('care-state','care-lga');renderFacilities()});
